### ISSUE TITLE
incorrect L2 RPC chain id on op-node

### ISSUE THREAD

**Issue by kookin** [mantlenetworkio/mantle-v2#188]
Followed the procedure. networks/mainnet/genesis.json and chain iD is set to 5000 as expected. OP_NODE_L1_ETH_RPC in docker-compose file is pointing to our internal node. Where else should I be checking to mitigate this error?

t=2024-11-19T14:33:21+0000 lvl=eror msg="Error initializing the rollup node" err="incorrect L2 RPC chain id, expected from config 5000, obtained from client 1"
t=2024-11-19T14:33:21+0000 lvl=eror msg="Unable to create the rollup node"   error="incorrect L2 RPC chain id, expected from config 5000, obtained from client 1"
t=2024-11-19T14:33:21+0000 lvl=crit msg="Application failed"                 message="incorrect L2 RPC chain id, expected from config 5000, obtained from client 1"

**Comment by kookin** [comment]
typo in docker compose file.

**Comment by johnnyji-dev** [comment]
@kookin 
Hello, I have the same issue.
Did you modify docker-compose-mainnetv2.yml?
Which part did you modify, and how did you change it?

**Comment by kookin** [comment]
first check that you're using the right images:

op-geth:
    image: mantlenetworkio/op-geth:v1.0.0-alpha.4

op-node:
    image: mantlenetworkio/op-node:v1.0.0-alpha.3

Other images did not work.

Make sure your volumes are mapped correctly, E.g.

op-geth
volumes:
      - <secret dir>:/secret/
      - <mainnet-geth dir>:/db/geth/

Op-node
volumes:
      - <secret dir>:/secret/
      - /<your-dir>/rollup.json:/config/rollup.json

Finally make sure you download the latest snapshot using gitHub instructions. First stop both containers / services & remove /chaindata dir. Download, extract snapshot data, then restart containers using docker compose.

**Comment by johnnyji-dev** [comment]
> first check that you're using the right images:
> 
> op-geth: image: mantlenetworkio/op-geth:v1.0.0-alpha.4
> 
> op-node: image: mantlenetworkio/op-node:v1.0.0-alpha.3
> 
> Other images did not work.
> 
> Make sure your volumes are mapped correctly, E.g.
> 
> op-geth volumes: - :/secret/ - :/db/geth/
> 
> Op-node volumes: - :/secret/ - //rollup.json:/config/rollup.json
> 
> Finally make sure you download the latest snapshot using gitHub instructions. First stop both containers / services & remove /chaindata dir. Download, extract snapshot data, then restart containers using docker compose.

Thanks for ur feedback, I can also run the node. ^^/
